"""add image_url and tags to resources

Revision ID: 4364d92f5261
Revises: 8c5e7f1e9a21
Create Date: 2026-04-19 01:19:25.656306

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4364d92f5261"
down_revision = "8c5e7f1e9a21"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bookings",
        "status",
        existing_type=postgresql.ENUM("confirmed", "cancelled", "pending", name="booking_status"),
        nullable=False,
    )
    op.alter_column(
        "bookings", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False
    )
    op.add_column("resources", sa.Column("image_url", sa.Text(), nullable=True))
    op.add_column("resources", sa.Column("tags", sa.JSON(), nullable=True))
    op.alter_column("resources", "capacity", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("resources", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "resources", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False
    )
    op.alter_column(
        "users", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True
    )
    op.alter_column(
        "resources", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True
    )
    op.alter_column("resources", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("resources", "capacity", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("resources", "tags")
    op.drop_column("resources", "image_url")
    op.alter_column(
        "bookings", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True
    )
    op.alter_column(
        "bookings",
        "status",
        existing_type=postgresql.ENUM("confirmed", "cancelled", "pending", name="booking_status"),
        nullable=True,
    )
    # ### end Alembic commands ###
